name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Get new version
        uses: arwynfr/actions-conventional-versioning/get-newVersion@v3
        id: new-version
        with:
          allow-additional-modifiers: true
          feat-upgrades-minor: false
          strict-types: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src
          file: src/ArwynFr.Authentication.OpenIdConnect.Discord/Dockerfile
          push: true
          tags: arwynfr/discord-oidc-provider:${{ steps.new-version.outputs.next-version }}

      - name: Publish new version
        uses: arwynfr/actions-conventional-versioning@v3
        with:
          allow-additional-modifiers: true
          feat-upgrades-minor: false
          strict-types: true
