name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**']

env:
  PROJECT: ArwynFr.Authentication.OpenIdConnect.Discord

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      
      - name: Get new version
        uses: arwynfr/actions-conventional-versioning/get-newVersion@v1
        id: new-version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: src
          file: ${{env.PROJECT}}/Dockerfile
          push: true
          tags: arwynfr/discord-oidc-provider:${{ steps.new-version.outputs.next-version }}

      - name: Publish new version
        uses: arwynfr/actions-conventional-versioning@v1
        with:
          pattern: ''