name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - run: docker build src --file src/ArwynFr.Authentication.OpenIdConnect.Discord/Dockerfile