name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  PROJECT: ArwynFr.Authentication.OpenIdConnect.Discord

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - run: docker build src --file ${{ env.PROJECT }}/Dockerfile